### ISSUE TITLE
Unrecognized command: define-eval

### ISSUE THREAD

**Issue by wqvbjhc** [gustavla/fractalnet#1]
when i run crox train.crox.prototxt > train.prototxt, error happen:

> ERROR globals.crox:2 Unrecognized command: define-eval

why? can anybody help me?

**Comment by gustavla** [comment]
Sorry about that, this function was still sitting on my computer. It has been pushed to the crox repository and the version has been updated. If you installed it through pip, `pip install -U crox` should be enough to fix this.
